# Generated by Django 3.2.4 on 2021-06-26 17:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0002_userdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blogs',
        ),
        migrations.RenameModel(
            old_name='Userdata',
            new_name='Userdatas',
        ),
    ]
